<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductsTableSeeder extends Seeder
{
    public function run(): void
    {
        
        $shoes = [
            [
                'name' => 'Nike Air Max Sports Shoes',
                'price' => 120.00,
                'sale_price' => 99.00,
                'stock_quantity' => 50,
                'sku' => 'SH001',
                'description' => 'Comfortable sports shoes with premium cushioning.',
                'short_description' => 'Premium sports shoes',
                'rating' => 4.8,
                'sold_count' => 1247,
                'is_featured' => true,
                
                'image_url' => 'images/products/shoes5.jpg',
            ],
            [
                'name' => 'Adidas Ultraboost Running Shoes',
                'price' => 180.00,
                'sale_price' => 149.00,
                'stock_quantity' => 40,
                'sku' => 'SH002',
                'description' => 'Lightweight running shoes with responsive cushioning.',
                'short_description' => 'Ultra-light running shoes',
                'rating' => 4.9,
                'sold_count' => 856,
                'is_featured' => true,
                'image_url' => 'images/products/running.jpg',
            ],
            [
                'name' => 'Puma Sneakers Casual',
                'price' => 80.00,
                'sale_price' => 65.00,
                'stock_quantity' => 60,
                'sku' => 'SH003',
                'description' => 'Stylish casual sneakers perfect for everyday wear.',
                'short_description' => 'Everyday casual sneakers',
                'rating' => 4.5,
                'sold_count' => 634,
                'is_featured' => false,
                'image_url' => 'images/products/running shoes.jpg',
            ],
            [
                'name' => 'New Balance 990v5',
                'price' => 95.00,
                'sale_price' => 79.00,
                'stock_quantity' => 35,
                'sku' => 'SH004',
                'description' => 'Classic New Balance sneakers with superior comfort.',
                'short_description' => 'Classic comfort sneakers',
                'rating' => 4.7,
                'sold_count' => 523,
                'is_featured' => false,
                'image_url' => 'images/products/shoes2.jpg',
            ],
            [
                'name' => 'Converse Chuck Taylor',
                'price' => 70.00,
                'sale_price' => 55.00,
                'stock_quantity' => 45,
                'sku' => 'SH005',
                'description' => 'Iconic Converse sneakers that never go out of style.',
                'short_description' => 'Iconic casual sneakers',
                'rating' => 4.4,
                'sold_count' => 2134,
                'is_featured' => false,
                'image_url' => 'images/products/shoes9.jpg',
            ],
        ];

        $watches = [
            [
                'name' => 'Apple Watch Series 9',
                'price' => 399.00,
                'sale_price' => 349.00,
                'stock_quantity' => 30,
                'sku' => 'WT001',
                'description' => 'Latest Apple Watch with advanced health features.',
                'short_description' => 'Premium smartwatch',
                'rating' => 4.9,
                'sold_count' => 3245,
                'is_featured' => true,
                'image_url' => 'images/products/smart watch4.jpg',
            ],
            [
                'name' => 'Samsung Galaxy Watch 6',
                'price' => 299.00,
                'sale_price' => 259.00,
                'stock_quantity' => 25,
                'sku' => 'WT002',
                'description' => 'Powerful Android smartwatch with rotating bezel.',
                'short_description' => 'Android smartwatch',
                'rating' => 4.7,
                'sold_count' => 1876,
                'is_featured' => true,
                'image_url' => 'images/products/smaet watch6.jpg',
            ],
            [
                'name' => 'Sveston Classic Watch',
                'price' => 150.00,
                'sale_price' => 120.00,
                'stock_quantity' => 35,
                'sku' => 'WT003',
                'description' => 'Elegant classic watch with leather strap.',
                'short_description' => 'Elegant classic watch',
                'rating' => 4.5,
                'sold_count' => 987,
                'is_featured' => false,
                'image_url' => 'images/products/watch5.jpg',
            ],
            [
                'name' => 'Rolex Submariner Style',
                'price' => 250.00,
                'sale_price' => 199.00,
                'stock_quantity' => 15,
                'sku' => 'WT004',
                'description' => 'Luxury-inspired diver watch with stainless steel band.',
                'short_description' => 'Luxury dive watch',
                'rating' => 4.8,
                'sold_count' => 432,
                'is_featured' => false,
                'image_url' => 'images/products/watch6.jpg',
            ],
            [
                'name' => 'Casio G-Shock Digital',
                'price' => 120.00,
                'sale_price' => 99.00,
                'stock_quantity' => 40,
                'sku' => 'WT005',
                'description' => 'Durable digital watch with shock resistance.',
                'short_description' => 'Durable digital watch',
                'rating' => 4.6,
                'sold_count' => 1543,
                'is_featured' => false,
                'image_url' => 'images/products/watch15.jpg',
            ],
        ];

       
        $earbuds = [
            [
                'name' => 'Sony WF-1000XM5',
                'price' => 299.00,
                'sale_price' => 249.00,
                'stock_quantity' => 45,
                'sku' => 'EB001',
                'description' => 'Industry-leading noise cancellation with exceptional sound quality.',
                'short_description' => 'Best noise cancelling earbuds',
                'rating' => 4.9,
                'sold_count' => 4567,
                'is_featured' => true,
                'image_url' => 'images/products/bluetooth1.jpg',
            ],
            [
                'name' => 'Apple AirPods Pro 2',
                'price' => 249.00,
                'sale_price' => 199.00,
                'stock_quantity' => 40,
                'sku' => 'EB002',
                'description' => 'Adaptive audio with personalized spatial sound.',
                'short_description' => 'Apple premium earbuds',
                'rating' => 4.8,
                'sold_count' => 6789,
                'is_featured' => true,
                'image_url' => 'images/products/bluetooth3.jpg',
            ],
            [
                'name' => 'Samsung Galaxy Buds 3',
                'price' => 179.00,
                'sale_price' => 149.00,
                'stock_quantity' => 35,
                'sku' => 'EB003',
                'description' => 'Premium sound quality with intelligent noise control.',
                'short_description' => 'Samsung premium earbuds',
                'rating' => 4.6,
                'sold_count' => 2345,
                'is_featured' => false,
                'image_url' => 'images/products/bluetooth5.jpg',
            ],
            [
                'name' => 'Bose QuietComfort Earbuds',
                'price' => 279.00,
                'sale_price' => 229.00,
                'stock_quantity' => 30,
                'sku' => 'EB004',
                'description' => 'Legendary Bose sound with exceptional noise cancellation.',
                'short_description' => 'Bose noise cancelling earbuds',
                'rating' => 4.7,
                'sold_count' => 3456,
                'is_featured' => false,
                'image_url' => 'images/products/bluetooth3.jpg',
            ],
            [
                'name' => 'Jabra Elite 10',
                'price' => 199.00,
                'sale_price' => 169.00,
                'stock_quantity' => 25,
                'sku' => 'EB005',
                'description' => 'Premium earbuds with excellent call quality.',
                'short_description' => 'Premium call quality earbuds',
                'rating' => 4.5,
                'sold_count' => 1234,
                'is_featured' => false,
                'image_url' => 'images/products/bluetooth.jpg',
            ],
        ];

        
        $sunglasses = [
            [
                'name' => 'Ray-Ban Aviator Classic',
                'price' => 149.00,
                'sale_price' => 119.00,
                'stock_quantity' => 30,
                'sku' => 'SG001',
                'description' => 'Iconic aviator sunglasses with polarized lenses.',
                'short_description' => 'Classic aviator sunglasses',
                'rating' => 4.5,
                'sold_count' => 5432,
                'is_featured' => true,
                'image_url' => 'images/products/glasses1.jpg',
            ],
            [
                'name' => 'Oakley Holbrook Sunglasses',
                'price' => 179.00,
                'sale_price' => 149.00,
                'stock_quantity' => 25,
                'sku' => 'SG002',
                'description' => 'Sports-inspired sunglasses with Oakley High Definition Optics.',
                'short_description' => 'Sports sunglasses',
                'rating' => 4.6,
                'sold_count' => 2341,
                'is_featured' => false,
                'image_url' => 'images/products/glasses3.jpg',
            ],
            [
                'name' => 'Prada Cat Eye Sunglasses',
                'price' => 220.00,
                'sale_price' => 189.00,
                'stock_quantity' => 20,
                'sku' => 'SG003',
                'description' => 'Fashion-forward cat eye sunglasses with UV protection.',
                'short_description' => 'Designer cat eye sunglasses',
                'rating' => 4.4,
                'sold_count' => 876,
                'is_featured' => false,
                'image_url' => 'images/products/glasses4.jpg',
            ],
            [
                'name' => 'Persol PO Polarized',
                'price' => 199.00,
                'sale_price' => 169.00,
                'stock_quantity' => 15,
                'sku' => 'SG004',
                'description' => 'Italian crafted sunglasses with polarized lenses.',
                'short_description' => 'Italian polarized sunglasses',
                'rating' => 4.7,
                'sold_count' => 654,
                'is_featured' => false,
                'image_url' => 'images/products/glasses5.jpg',
            ],
            [
                'name' => 'Gucci GG Sunglasses',
                'price' => 350.00,
                'sale_price' => 299.00,
                'stock_quantity' => 10,
                'sku' => 'SG005',
                'description' => 'Luxury designer sunglasses with iconic GG logo.',
                'short_description' => 'Designer luxury sunglasses',
                'rating' => 4.8,
                'sold_count' => 432,
                'is_featured' => true,
                'image_url' => 'images/products/glasses9.jpg',
            ],
        ];

        
        $mobileAccessories = [
            [
                'name' => 'Spigen iPhone Case',
                'price' => 25.00,
                'sale_price' => 19.99,
                'stock_quantity' => 100,
                'sku' => 'MA001',
                'description' => 'Durable protective case with military-grade drop protection.',
                'short_description' => 'Premium protective case',
                'rating' => 4.7,
                'sold_count' => 8765,
                'is_featured' => true,
                'image_url' => 'images/products/mobile1.jpg',
            ],
            [
                'name' => 'OtterBox Defender Case',
                'price' => 35.00,
                'sale_price' => 29.99,
                'stock_quantity' => 80,
                'sku' => 'MA002',
                'description' => 'Ultimate protection with multi-layer defense system.',
                'short_description' => 'Ultimate protection case',
                'rating' => 4.8,
                'sold_count' => 6543,
                'is_featured' => false,
                'image_url' => 'images/products/mobile2.jpg',
            ],
            [
                'name' => 'PopSocket Phone Grip',
                'price' => 15.00,
                'sale_price' => 12.99,
                'stock_quantity' => 150,
                'sku' => 'MA003',
                'description' => 'Expandable phone grip with pop-out design.',
                'short_description' => 'Phone grip accessory',
                'rating' => 4.4,
                'sold_count' => 4321,
                'is_featured' => false,
                'image_url' => 'images/products/mobile4.jpg',
            ],
            [
                'name' => 'Belkin Screen Protector',
                'price' => 20.00,
                'sale_price' => 15.99,
                'stock_quantity' => 200,
                'sku' => 'MA004',
                'description' => 'Premium tempered glass screen protector.',
                'short_description' => 'Premium screen protector',
                'rating' => 4.6,
                'sold_count' => 9876,
                'is_featured' => false,
                'image_url' => 'images/products/mobile3.jpg',
            ],
            [
                'name' => 'Mophie Wireless Charger',
                'price' => 40.00,
                'sale_price' => 34.99,
                'stock_quantity' => 50,
                'sku' => 'MA005',
                'description' => 'Fast wireless charging pad compatible with all Qi devices.',
                'short_description' => 'Fast wireless charger',
                'rating' => 4.5,
                'sold_count' => 2345,
                'is_featured' => false,
                'image_url' => 'images/products/charger6.jpg',
            ],
        ];

        
        $powerBanks = [
            [
                'name' => 'Anker 20000mAh Power Bank',
                'price' => 79.00,
                'sale_price' => 59.00,
                'stock_quantity' => 50,
                'sku' => 'PB001',
                'description' => 'High-capacity power bank with fast charging.',
                'short_description' => 'High capacity power bank',
                'rating' => 4.7,
                'sold_count' => 8765,
                'is_featured' => true,
                'image_url' => 'images/products/ankercharger.jpg',
            ],
            [
                'name' => 'Samsung 10000mAh Slim Power Bank',
                'price' => 49.00,
                'sale_price' => 39.00,
                'stock_quantity' => 60,
                'sku' => 'PB002',
                'description' => 'Ultra-slim power bank perfect for travel.',
                'short_description' => 'Slim portable power bank',
                'rating' => 4.4,
                'sold_count' => 3456,
                'is_featured' => false,
                'image_url' => 'images/products/samsungcharger.jpg',
            ],
            [
                'name' => 'Xiaomi 20000mAh Power Bank',
                'price' => 55.00,
                'sale_price' => 45.00,
                'stock_quantity' => 40,
                'sku' => 'PB003',
                'description' => 'High-capacity power bank with dual USB outputs.',
                'short_description' => 'High capacity dual USB',
                'rating' => 4.6,
                'sold_count' => 5432,
                'is_featured' => false,
                'image_url' => 'images/products/xiaomi.jpg',
            ],
            [
                'name' => 'Belkin 5000mAh Mini Power Bank',
                'price' => 30.00,
                'sale_price' => 24.99,
                'stock_quantity' => 80,
                'sku' => 'PB004',
                'description' => 'Compact power bank for emergency charging.',
                'short_description' => 'Compact emergency charger',
                'rating' => 4.3,
                'sold_count' => 2345,
                'is_featured' => false,
                'image_url' => 'images/products/belkin.jpg',
            ],
            [
                'name' => 'Mophie PowerStation Plus',
                'price' => 65.00,
                'sale_price' => 54.99,
                'stock_quantity' => 30,
                'sku' => 'PB005',
                'description' => 'Integrated power bank with built-in cables.',
                'short_description' => 'All-in-one power bank',
                'rating' => 4.5,
                'sold_count' => 1234,
                'is_featured' => false,
                'image_url' => 'images/products/mophiecharger.jpg',
            ],
        ];

      
        $chargers = [
            [
                'name' => '65W GaN Fast Charger',
                'price' => 45.00,
                'sale_price' => 35.00,
                'stock_quantity' => 100,
                'sku' => 'CH001',
                'description' => 'GaN technology fast charger for laptops and phones.',
                'short_description' => 'GaN fast charger',
                'rating' => 4.8,
                'sold_count' => 4321,
                'is_featured' => true,
                'image_url' => 'images/products/charger1.jpg',
            ],
            [
                'name' => '20W USB-C PD Charger',
                'price' => 25.00,
                'sale_price' => 19.00,
                'stock_quantity' => 80,
                'sku' => 'CH002',
                'description' => 'Fast USB-C charger for iPhone and Android devices.',
                'short_description' => 'USB-C fast charger',
                'rating' => 4.5,
                'sold_count' => 5678,
                'is_featured' => false,
                'image_url' => 'images/products/charger2.jpg',
            ],
            [
                'name' => 'Samsung Super Fast Charger',
                'price' => 30.00,
                'sale_price' => 24.99,
                'stock_quantity' => 60,
                'sku' => 'CH003',
                'description' => 'Super fast charging for Samsung Galaxy devices.',
                'short_description' => 'Samsung fast charger',
                'rating' => 4.6,
                'sold_count' => 3456,
                'is_featured' => false,
                'image_url' => 'images/products/charger3.jpg',
            ],
            [
                'name' => 'Apple USB-C Charger',
                'price' => 35.00,
                'sale_price' => 29.99,
                'stock_quantity' => 50,
                'sku' => 'CH004',
                'description' => 'Official Apple USB-C charger for MacBook and iPad.',
                'short_description' => 'Apple USB-C charger',
                'rating' => 4.7,
                'sold_count' => 2345,
                'is_featured' => false,
                'image_url' => 'images/products/charger5.jpg',
            ],
            [
                'name' => 'Ugreen 3-Port Charger',
                'price' => 28.00,
                'sale_price' => 22.99,
                'stock_quantity' => 70,
                'sku' => 'CH005',
                'description' => 'Multi-port charger with 3 USB outputs for all devices.',
                'short_description' => 'Multi-port USB charger',
                'rating' => 4.4,
                'sold_count' => 1234,
                'is_featured' => false,
                'image_url' => 'images/products/3portcharger.jpg',
            ],
        ];

     
        $categoryMap = [
            1 => $shoes,
            2 => $watches,
            3 => $earbuds,
            4 => $sunglasses,
            5 => $mobileAccessories,
            6 => $powerBanks,
            7 => $chargers,
        ];

        foreach ($categoryMap as $categoryId => $products) {
            foreach ($products as $productData) {
                $productData['category_id'] = $categoryId;
                $productData['slug'] = Str::slug($productData['name']) . '-' . uniqid();
                $productData['is_active'] = true;
                
                $product = Product::create($productData);
                
             
                ProductImage::create([
                    'product_id' => $product->id,
                    'image_url' => $productData['image_url'],
                    'alt_text' => $productData['name'],
                    'is_primary' => true,
                    'sort_order' => 0,
                ]);
            }
        }
    }
}