<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductsTableSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ============ SHOES (Category ID: 1) ============
            [
                'name' => 'Nike Air Max Sports Shoes',
                'slug' => Str::slug('Nike Air Max Sports Shoes'),
                'price' => 120.00,
                'stock_quantity' => 50,
                'category_id' => 1,
                'sku' => 'SH001',
                'description' => 'Comfortable sports shoes with premium cushioning for all-day wear. Perfect for running and casual outings.',
                'short_description' => 'Premium sports shoes with superior comfort',
                'rating' => 4.8,
                'sold_count' => 1247,
                'is_active' => true,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Adidas Ultraboost Running Shoes',
                'slug' => Str::slug('Adidas Ultraboost Running Shoes'),
                'price' => 180.00,
                'stock_quantity' => 40,
                'category_id' => 1,
                'sku' => 'SH002',
                'description' => 'Lightweight running shoes with responsive cushioning for maximum performance.',
                'short_description' => 'Ultra-light running shoes',
                'rating' => 4.9,
                'sold_count' => 856,
                'is_active' => true,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Puma Sneakers Casual',
                'slug' => Str::slug('Puma Sneakers Casual'),
                'price' => 80.00,
                'stock_quantity' => 60,
                'category_id' => 1,
                'sku' => 'SH003',
                'description' => 'Stylish casual sneakers perfect for everyday wear. Comfortable and durable.',
                'short_description' => 'Everyday casual sneakers',
                'rating' => 4.5,
                'sold_count' => 634,
                'is_active' => true,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'New Balance 990v5',
                'slug' => Str::slug('New Balance 990v5'),
                'price' => 95.00,
                'stock_quantity' => 35,
                'category_id' => 1,
                'sku' => 'SH004',
                'description' => 'Classic New Balance sneakers with superior comfort and timeless design.',
                'short_description' => 'Classic comfort sneakers',
                'rating' => 4.7,
                'sold_count' => 523,
                'is_active' => true,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Converse Chuck Taylor',
                'slug' => Str::slug('Converse Chuck Taylor'),
                'price' => 70.00,
                'stock_quantity' => 45,
                'category_id' => 1,
                'sku' => 'SH005',
                'description' => 'Iconic Converse sneakers that never go out of style. Perfect for casual looks.',
                'short_description' => 'Iconic casual sneakers',
                'rating' => 4.4,
                'sold_count' => 2134,
                'is_active' => true,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400&h=400&fit=crop',
            ],

            // ============ WATCHES (Category ID: 2) ============
            [
                'name' => 'Apple Watch Series 9',
                'slug' => Str::slug('Apple Watch Series 9'),
                'price' => 399.00,
                'stock_quantity' => 30,
                'category_id' => 2,
                'sku' => 'WT001',
                'description' => 'Latest Apple Watch with advanced health features and always-on display.',
                'short_description' => 'Premium smartwatch',
                'rating' => 4.9,
                'sold_count' => 3245,
                'is_active' => true,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Samsung Galaxy Watch 6',
                'slug' => Str::slug('Samsung Galaxy Watch 6'),
                'price' => 299.00,
                'stock_quantity' => 25,
                'category_id' => 2,
                'sku' => 'WT002',
                'description' => 'Powerful Android smartwatch with rotating bezel and comprehensive fitness tracking.',
                'short_description' => 'Android smartwatch',
                'rating' => 4.7,
                'sold_count' => 1876,
                'is_active' => true,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Sveston Classic Watch',
                'slug' => Str::slug('Sveston Classic Watch'),
                'price' => 150.00,
                'stock_quantity' => 35,
                'category_id' => 2,
                'sku' => 'WT003',
                'description' => 'Elegant classic watch with leather strap and minimalist dial.',
                'short_description' => 'Elegant classic watch',
                'rating' => 4.5,
                'sold_count' => 987,
                'is_active' => true,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Rolex Submariner Style',
                'slug' => Str::slug('Rolex Submariner Style'),
                'price' => 250.00,
                'stock_quantity' => 15,
                'category_id' => 2,
                'sku' => 'WT004',
                'description' => 'Luxury-inspired diver watch with stainless steel band and ceramic bezel.',
                'short_description' => 'Luxury dive watch',
                'rating' => 4.8,
                'sold_count' => 432,
                'is_active' => true,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
            ],

            // ============ EARBUDS (Category ID: 3) ============
            [
                'name' => 'Sony WF-1000XM5',
                'slug' => Str::slug('Sony WF-1000XM5'),
                'price' => 299.00,
                'stock_quantity' => 45,
                'category_id' => 3,
                'sku' => 'EB001',
                'description' => 'Industry-leading noise cancellation with exceptional sound quality.',
                'short_description' => 'Best noise cancelling earbuds',
                'rating' => 4.9,
                'sold_count' => 4567,
                'is_active' => true,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Apple AirPods Pro 2',
                'slug' => Str::slug('Apple AirPods Pro 2'),
                'price' => 249.00,
                'stock_quantity' => 40,
                'category_id' => 3,
                'sku' => 'EB002',
                'description' => 'Adaptive audio with personalized spatial sound.',
                'short_description' => 'Apple premium earbuds',
                'rating' => 4.8,
                'sold_count' => 6789,
                'is_active' => true,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Samsung Galaxy Buds 3',
                'slug' => Str::slug('Samsung Galaxy Buds 3'),
                'price' => 179.00,
                'stock_quantity' => 35,
                'category_id' => 3,
                'sku' => 'EB003',
                'description' => 'Premium sound quality with intelligent noise control.',
                'short_description' => 'Samsung premium earbuds',
                'rating' => 4.6,
                'sold_count' => 2345,
                'is_active' => true,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Bose QuietComfort Earbuds',
                'slug' => Str::slug('Bose QuietComfort Earbuds'),
                'price' => 279.00,
                'stock_quantity' => 30,
                'category_id' => 3,
                'sku' => 'EB004',
                'description' => 'Legendary Bose sound with exceptional noise cancellation.',
                'short_description' => 'Bose noise cancelling earbuds',
                'rating' => 4.7,
                'sold_count' => 3456,
                'is_active' => true,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop',
            ],

            // ============ SUNGLASSES (Category ID: 4) ============
            [
                'name' => 'Ray-Ban Aviator Classic',
                'slug' => Str::slug('Ray-Ban Aviator Classic'),
                'price' => 149.00,
                'stock_quantity' => 30,
                'category_id' => 4,
                'sku' => 'SG001',
                'description' => 'Iconic aviator sunglasses with polarized lenses.',
                'short_description' => 'Classic aviator sunglasses',
                'rating' => 4.5,
                'sold_count' => 5432,
                'is_active' => true,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Oakley Holbrook Sunglasses',
                'slug' => Str::slug('Oakley Holbrook Sunglasses'),
                'price' => 179.00,
                'stock_quantity' => 25,
                'category_id' => 4,
                'sku' => 'SG002',
                'description' => 'Sports-inspired sunglasses with Oakley High Definition Optics.',
                'short_description' => 'Sports sunglasses',
                'rating' => 4.6,
                'sold_count' => 2341,
                'is_active' => true,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Prada Cat Eye Sunglasses',
                'slug' => Str::slug('Prada Cat Eye Sunglasses'),
                'price' => 220.00,
                'stock_quantity' => 20,
                'category_id' => 4,
                'sku' => 'SG003',
                'description' => 'Fashion-forward cat eye sunglasses with UV protection.',
                'short_description' => 'Designer cat eye sunglasses',
                'rating' => 4.4,
                'sold_count' => 876,
                'is_active' => true,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1532300488142-78a7da1c9c2e?w=400&h=400&fit=crop',
            ],

            // ============ POWER BANKS (Category ID: 6) ============
            [
                'name' => 'Anker 20000mAh Power Bank',
                'slug' => Str::slug('Anker 20000mAh Power Bank'),
                'price' => 79.00,
                'stock_quantity' => 50,
                'category_id' => 6,
                'sku' => 'PB001',
                'description' => 'High-capacity power bank with fast charging for all devices.',
                'short_description' => 'High capacity power bank',
                'rating' => 4.7,
                'sold_count' => 8765,
                'is_active' => true,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1609592425212-7e7c6e709ae1?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Samsung 10000mAh Slim Power Bank',
                'slug' => Str::slug('Samsung 10000mAh Slim Power Bank'),
                'price' => 49.00,
                'stock_quantity' => 60,
                'category_id' => 6,
                'sku' => 'PB002',
                'description' => 'Ultra-slim power bank perfect for travel and everyday use.',
                'short_description' => 'Slim portable power bank',
                'rating' => 4.4,
                'sold_count' => 3456,
                'is_active' => true,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1609592425212-7e7c6e709ae1?w=400&h=400&fit=crop',
            ],

            // ============ CHARGERS (Category ID: 7) ============
            [
                'name' => '65W GaN Fast Charger',
                'slug' => Str::slug('65W GaN Fast Charger'),
                'price' => 45.00,
                'stock_quantity' => 100,
                'category_id' => 7,
                'sku' => 'CH001',
                'description' => 'GaN technology fast charger for laptops and phones.',
                'short_description' => 'GaN fast charger',
                'rating' => 4.8,
                'sold_count' => 4321,
                'is_active' => true,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1585336261022-680e9ce1f01b?w=400&h=400&fit=crop',
            ],
            [
                'name' => '20W USB-C PD Charger',
                'slug' => Str::slug('20W USB-C PD Charger'),
                'price' => 25.00,
                'stock_quantity' => 80,
                'category_id' => 7,
                'sku' => 'CH002',
                'description' => 'Fast USB-C charger for iPhone and Android devices.',
                'short_description' => 'USB-C fast charger',
                'rating' => 4.5,
                'sold_count' => 5678,
                'is_active' => true,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1585336261022-680e9ce1f01b?w=400&h=400&fit=crop',
            ],
        ];

        foreach ($products as $productData) {
            // ✅ Create product
            $product = Product::create($productData);
            
            // ✅ Create primary product image
            ProductImage::create([
                'product_id' => $product->id,
                'image_url' => $productData['image_url'],
                'alt_text' => $productData['name'],
                'is_primary' => true,
                'sort_order' => 0,  // ✅ FIXED: sort_o?rder se sort_order kiya
            ]);

            // ✅ Create additional images (2-3 extra)
            $additionalImages = [
                'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop',
                'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=400&h=400&fit=crop',
                'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
                'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=400&h=400&fit=crop',
                'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400&h=400&fit=crop',
            ];

            shuffle($additionalImages);
            $extraCount = rand(1, 2);
            for ($i = 0; $i < $extraCount; $i++) {
                ProductImage::create([
                    'product_id' => $product->id,
                    'image_url' => $additionalImages[$i],
                    'alt_text' => $productData['name'] . ' - Image ' . ($i + 2),
                    'is_primary' => false,
                    'sort_order' => $i + 1,
                ]);
            }
        }
    }
}